from .user_kb import (
    cancel_kb,
    category_kb,
    gallery_kb,
    materials_kb,
    sizes_kb,
    confirm_item_kb,
    more_items_kb,
    cart_view_kb,
    deadline_kb,
    final_confirm_kb,
    main_menu_kb,
    orders_list_kb,
    pay_request_kb,
    language_picker_kb,
    review_kb,
    promo_kb,
    contact_request_kb,
    location_request_kb,
    hide_reply_kb,
)
from .admin_kb import (
    admin_panel_kb,
    admin_orders_menu_kb,
    admin_order_actions_kb,
    admin_broadcast_target_kb,
    admin_catalog_menu_kb,
    admin_stats_kb,
    admin_back_kb,
    admin_pagination_kb,
    admin_admins_list_kb,
    admin_role_picker_kb,
    admin_promo_menu_kb,
    admin_promo_list_kb,
    admin_promo_actions_kb,
    admin_reviews_kb,
    admin_settings_kb,
    admin_confirm_delete_kb,
)

__all__ = [
    # user
    "cancel_kb", "category_kb", "gallery_kb", "materials_kb", "sizes_kb",
    "confirm_item_kb", "more_items_kb", "cart_view_kb", "deadline_kb",
    "final_confirm_kb", "main_menu_kb", "orders_list_kb", "pay_request_kb",
    "language_picker_kb", "review_kb", "promo_kb",
    "contact_request_kb", "location_request_kb", "hide_reply_kb",
    # admin
    "admin_panel_kb", "admin_orders_menu_kb", "admin_order_actions_kb",
    "admin_broadcast_target_kb", "admin_catalog_menu_kb", "admin_stats_kb",
    "admin_back_kb", "admin_pagination_kb",
    "admin_admins_list_kb", "admin_role_picker_kb",
    "admin_promo_menu_kb", "admin_promo_list_kb", "admin_promo_actions_kb",
    "admin_reviews_kb", "admin_settings_kb", "admin_confirm_delete_kb",
]
